# Generated by Django 5.2.11 on 2026-03-06 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('shop_name', models.CharField(default="🛒 Do'kon", max_length=150, verbose_name="Do'kon nomi")),
                ('shop_logo', models.ImageField(blank=True, null=True, upload_to='settings/logo/', verbose_name="Do'kon logotipi")),
                ('contact_phone', models.CharField(blank=True, max_length=30, verbose_name='Aloqa uchun telefon')),
                ('contact_telegram', models.CharField(blank=True, max_length=100, verbose_name='Telegram Username/Link')),
            ],
            options={
                'verbose_name': 'Sayt sozlamalari',
                'verbose_name_plural': 'Sayt sozlamalari',
                'db_table': 'site_settings',
            },
        ),
    ]
