# Generated by Django 5.2.11 on 2026-03-06 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='hero_button_text',
            field=models.CharField(default="Batafsil ko'rish", max_length=100, verbose_name='Tugma matni'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='hero_image',
            field=models.ImageField(blank=True, null=True, upload_to='settings/hero/', verbose_name='Hero Poster Rasmi'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='hero_link',
            field=models.CharField(default='/', max_length=255, verbose_name='Tugma havolasi (URL)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='hero_subtitle',
            field=models.CharField(default="YANGI TO'PLAM - CHEGIRMA", max_length=200, verbose_name='Hero Qism-sarlavha (Kichik matn)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='hero_title',
            field=models.CharField(default='CURATED COLLECTIONS - OLD MONEY ELEGANCE', max_length=200, verbose_name='Hero Sarlavha (Katta matn)'),
        ),
    ]
