# Generated by Django 5.0.8 on 2026-03-01 06:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BotSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bot_token', models.CharField(max_length=255, verbose_name='Bot Token')),
                ('admin_chat_id', models.CharField(max_length=100, verbose_name='Admin Chat ID')),
                ('payment_card_number', models.CharField(blank=True, max_length=30, verbose_name="To'lov karta raqami")),
                ('payment_card_holder', models.CharField(blank=True, max_length=200, verbose_name='Karta egasi')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
            ],
            options={
                'verbose_name': 'Bot Sozlamalari',
                'verbose_name_plural': 'Bot Sozlamalari',
                'db_table': 'bot_settings',
            },
        ),
        migrations.CreateModel(
            name='PaymentScreenshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('screenshot', models.ImageField(upload_to='payment_screenshots/%Y/%m/', verbose_name='Skrinshot')),
                ('is_confirmed', models.BooleanField(default=False, verbose_name='Tasdiqlangan')),
                ('confirmed_by', models.CharField(blank=True, max_length=150, verbose_name='Kim tasdiqladi')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_screenshots', to='orders.order', verbose_name='Buyurtma')),
            ],
            options={
                'verbose_name': "To'lov skrinshoti",
                'verbose_name_plural': "To'lov skrinshotlari",
                'db_table': 'payment_screenshots',
                'ordering': ['-created_at'],
            },
        ),
    ]
