# Generated by Django 5.2.11 on 2026-03-01 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_bot', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='botsettings',
            name='admin_chat_id',
        ),
        migrations.RemoveField(
            model_name='botsettings',
            name='bot_token',
        ),
        migrations.AddField(
            model_name='botsettings',
            name='admin_phone',
            field=models.CharField(blank=True, max_length=30, verbose_name='Admin Telefon Raqami (masalan: +998901234567)'),
        ),
        migrations.AddField(
            model_name='botsettings',
            name='api_hash',
            field=models.CharField(blank=True, max_length=100, verbose_name='API Hash'),
        ),
        migrations.AddField(
            model_name='botsettings',
            name='api_id',
            field=models.CharField(blank=True, max_length=50, verbose_name='API ID'),
        ),
    ]
