# Generated by Django 5.0.8 on 2026-03-01 06:32

import apps.orders.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('session_key', models.CharField(max_length=255, unique=True, verbose_name='Sessiya')),
            ],
            options={
                'verbose_name': 'Savat',
                'verbose_name_plural': 'Savatlar',
                'db_table': 'carts',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order_number', models.CharField(default=apps.orders.models.generate_order_number, max_length=20, unique=True, verbose_name='Buyurtma raqami')),
                ('phone_number', models.CharField(max_length=20, verbose_name='Telefon raqami')),
                ('telegram_username', models.CharField(blank=True, max_length=100, verbose_name='Telegram username')),
                ('telegram_chat_id', models.CharField(blank=True, max_length=50, verbose_name='Telegram Chat ID')),
                ('location', models.TextField(verbose_name='Manzil')),
                ('status', models.CharField(choices=[('UNPAID', "To'lov qilinmagan"), ('PAID', "To'lov qilindi"), ('COLLECTING', "Yig'ilyapti"), ('SHIPPING', "Yo'lda"), ('DELIVERED', 'Yetkazildi')], db_index=True, default='UNPAID', max_length=20, verbose_name='Holati')),
                ('total_amount', models.DecimalField(decimal_places=0, default=0, max_digits=14, verbose_name='Mahsulotlar narxi')),
                ('cargo_total', models.DecimalField(decimal_places=0, default=0, max_digits=14, verbose_name='Yetkazish narxi')),
                ('grand_total', models.DecimalField(decimal_places=0, default=0, max_digits=14, verbose_name='Jami summa')),
                ('note', models.TextField(blank=True, verbose_name='Izoh')),
            ],
            options={
                'verbose_name': 'Buyurtma',
                'verbose_name_plural': 'Buyurtmalar',
                'db_table': 'orders',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product_name', models.CharField(max_length=500, verbose_name='Mahsulot nomi')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Soni')),
                ('unit_price', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='Birlik narxi')),
                ('cargo_charge', models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='Yetkazish narxi')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order', verbose_name='Buyurtma')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.product', verbose_name='Mahsulot')),
            ],
            options={
                'verbose_name': 'Buyurtma elementi',
                'verbose_name_plural': 'Buyurtma elementlari',
                'db_table': 'order_items',
            },
        ),
        migrations.CreateModel(
            name='OrderStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('old_status', models.CharField(choices=[('UNPAID', "To'lov qilinmagan"), ('PAID', "To'lov qilindi"), ('COLLECTING', "Yig'ilyapti"), ('SHIPPING', "Yo'lda"), ('DELIVERED', 'Yetkazildi')], max_length=20, verbose_name='Oldingi holat')),
                ('new_status', models.CharField(choices=[('UNPAID', "To'lov qilinmagan"), ('PAID', "To'lov qilindi"), ('COLLECTING', "Yig'ilyapti"), ('SHIPPING', "Yo'lda"), ('DELIVERED', 'Yetkazildi')], max_length=20, verbose_name='Yangi holat')),
                ('changed_by', models.CharField(blank=True, max_length=150, verbose_name="Kim o'zgartirdi")),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='orders.order', verbose_name='Buyurtma')),
            ],
            options={
                'verbose_name': 'Holat tarixi',
                'verbose_name_plural': 'Holat tarixi',
                'db_table': 'order_status_history',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Soni')),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.cart', verbose_name='Savat')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product', verbose_name='Mahsulot')),
            ],
            options={
                'verbose_name': 'Savat elementi',
                'verbose_name_plural': 'Savat elementlari',
                'db_table': 'cart_items',
                'unique_together': {('cart', 'product')},
            },
        ),
    ]
