# Generated by Django 6.0.6 on 2026-06-22 07:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_color_product_colors'),
    ]

    operations = [
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=10, verbose_name="O'lcham nomi")),
                ('size_type', models.CharField(choices=[('NONE', "Yo'q"), ('CLOTHING', 'Kiyim'), ('SHOES', 'Poyabzal')], default='NONE', max_length=20, verbose_name="O'lcham turi")),
                ('ordering', models.IntegerField(default=0, verbose_name='Tartib')),
            ],
            options={
                'verbose_name': "O'lcham",
                'verbose_name_plural': "O'lchamlar",
                'db_table': 'sizes',
                'ordering': ['ordering', 'name'],
            },
        ),
        migrations.AddField(
            model_name='category',
            name='size_type',
            field=models.CharField(choices=[('NONE', "Yo'q"), ('CLOTHING', 'Kiyim'), ('SHOES', 'Poyabzal')], default='NONE', max_length=20, verbose_name="O'lcham turi"),
        ),
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, verbose_name='Nomi')),
                ('name_uz', models.CharField(max_length=255, null=True, verbose_name='Nomi')),
                ('name_ru', models.CharField(max_length=255, null=True, verbose_name='Nomi')),
                ('name_en', models.CharField(max_length=255, null=True, verbose_name='Nomi')),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True, verbose_name='Slug')),
                ('description', models.TextField(blank=True, verbose_name='Tavsif')),
                ('description_uz', models.TextField(blank=True, null=True, verbose_name='Tavsif')),
                ('description_ru', models.TextField(blank=True, null=True, verbose_name='Tavsif')),
                ('description_en', models.TextField(blank=True, null=True, verbose_name='Tavsif')),
                ('image', models.ImageField(blank=True, upload_to='collections/', verbose_name='Rasm')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('ordering', models.IntegerField(default=0, verbose_name='Tartib')),
                ('products', models.ManyToManyField(blank=True, related_name='collections', to='products.product', verbose_name='Mahsulotlar')),
            ],
            options={
                'verbose_name': "To'plam",
                'verbose_name_plural': "To'plamlar",
                'db_table': 'collections',
                'ordering': ['ordering', 'name'],
            },
        ),
        migrations.AddField(
            model_name='product',
            name='sizes',
            field=models.ManyToManyField(blank=True, related_name='products', to='products.size', verbose_name="O'lchamlar"),
        ),
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('stock', models.PositiveIntegerField(default=0, verbose_name='Zaxira')),
                ('price_override', models.DecimalField(blank=True, decimal_places=0, max_digits=12, null=True, verbose_name='Boshqa narx')),
                ('color', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.color', verbose_name='Rang')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='products.product', verbose_name='Mahsulot')),
                ('size', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.size', verbose_name="O'lcham")),
            ],
            options={
                'verbose_name': 'Mahsulot varianti',
                'verbose_name_plural': 'Mahsulot variantlari',
                'db_table': 'product_variants',
                'unique_together': {('product', 'color', 'size')},
            },
        ),
    ]
